In [1]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import pickle

le = preprocessing.LabelEncoder()

In [2]:
input_df = pd.read_csv('ObesityDataSet_raw_and_data_sinthetic.csv')
input_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [3]:
clean_df=input_df.drop(['FCVC','NCP','CH2O','FAF','TUE'],axis=1)
clean_df['family_history_with_overweight'].unique()
clean_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,Sometimes,no,no,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,Sometimes,yes,yes,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,Sometimes,no,no,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,Sometimes,no,no,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,Sometimes,no,no,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,Sometimes,no,no,Sometimes,Public_Transportation,Obesity_Type_III

In [4]:
le = preprocessing.LabelEncoder()

clean_df['Gender'] = le.fit_transform(clean_df['Gender'])
clean_df['family_history_with_overweight'] = le.fit_transform(clean_df['family_history_with_overweight'])
clean_df['FAVC'] = le.fit_transform(clean_df['FAVC'])
clean_df['CAEC'] = le.fit_transform(clean_df['CAEC'])
clean_df['SMOKE'] = le.fit_transform(clean_df['SMOKE'])
clean_df['SCC'] = le.fit_transform(clean_df['SCC'])
clean_df['CALC'] = le.fit_transform(clean_df['CALC'])
clean_df['MTRANS'] = le.fit_transform(clean_df['MTRANS'])
clean_df['NObeyesdad'] = le.fit_transform(clean_df['NObeyesdad'])

clean_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,0,21.000000,1.620000,64.000000,1,0,2,0,0,3,3,1
1,0,21.000000,1.520000,56.000000,1,0,2,1,1,2,3,1
2,1,23.000000,1.800000,77.000000,1,0,2,0,0,1,3,1
3,1,27.000000,1.800000,87.000000,0,0,2,0,0,1,4,5
4,1,22.000000,1.780000,89.800000,0,0,2,0,0,2,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,0,20.976842,1.710730,131.408528,1,1,2,0,0,2,3,4
2107,0,21.982942,1.748584,133.742943,1,1,2,0,0,2,3,4
2108,0,22.524036,1.752206,133.689352,1,1,2,0,0,2,3,4
2109,0,24.361936,1.739450,133.346641,1,1,2,0,0,2,3,4
2110,0,23.664709,1.738836,133.472641,1,1,2,0,0,2,3,4

In [5]:
clean_df[['Height','Weight']]=clean_df[['Height','Weight']].round(2)
clean_df['Age']=clean_df['Age'].astype(int)

In [6]:
scaler = preprocessing.MinMaxScaler()

clean_df[['Height','Weight','Age']] = scaler.fit_transform(clean_df[['Height','Weight','Age']])

In [7]:
clean_df

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS,NObeyesdad
0,0,0.148936,0.320755,0.186567,1,0,2,0,0,3,3,1
1,0,0.148936,0.132075,0.126866,1,0,2,1,1,2,3,1
2,1,0.191489,0.660377,0.283582,1,0,2,0,0,1,3,1
3,1,0.276596,0.660377,0.358209,0,0,2,0,0,1,4,5
4,1,0.170213,0.622642,0.379104,0,0,2,0,0,2,3,6
...,...,...,...,...,...,...,...,...,...,...,...,...
2106,0,0.127660,0.490566,0.689627,1,1,2,0,0,2,3,4
2107,0,0.148936,0.566038,0.707015,1,1,2,0,0,2,3,4
2108,0,0.170213,0.566038,0.706642,1,1,2,0,0,2,3,4
2109,0,0.212766,0.547170,0.704104,1,1,2,0,0,2,3,4
2110,0,0.191489,0.547170,0.705000,1,1,2,0,0,2,3,4

In [8]:
from sklearn.model_selection import train_test_split

X=clean_df.drop(['NObeyesdad'], axis=1)
y=clean_df['NObeyesdad']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3)

In [9]:
regr = RandomForestClassifier(max_depth=10, random_state=42)

In [10]:
regr.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, random_state=42)

In [11]:
y_pred_test = regr.predict(X_test)

In [12]:
accuracy_score(y_test, y_pred_test)

0.944794952681388

In [13]:
filename = 'finalized_model.sav'
filename_le = 'label_encoder.sav'
filename_minmax = 'min_max_scalar.sav'

pickle.dump(regr, open(filename, 'wb'))
pickle.dump(le, open(filename_le, 'wb'))
pickle.dump(scaler, open(filename_minmax, 'wb'))


# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, y_test)
print(result)

0.944794952681388

In [14]:
loaded_model.predict(X_test[:1])

array([2])

In [15]:
X_test[:1]

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,CAEC,SMOKE,SCC,CALC,MTRANS
1437,0,0.510638,0.188679,0.30597,1,1,2,0,0,2,0

In [22]:
loaded_model.predict([[1,1,1,2,0,0,2,0,0.340426,0.584906,0.544403]])

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([3])

In [17]:
row =[0,0.14893617,0.3275472,0.18656716,1,0,2,0,0,3,3,]
loaded_model.predict([row])

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])

In [23]:
labelEncoderFile = pickle.load(open(filename_le, 'rb'))
gender = labelEncoderFile.inverse_transform([[4][0]]) 
gender1 = labelEncoderFile.transform(['Obesity_Type_III'])

In [24]:
gender1

array([4])

In [25]:
gender

array(['Obesity_Type_III'], dtype=object)

In [26]:
MinMaxScalerFile = pickle.load(open(filename_minmax, 'rb'))
height=1.62
weight = 64
age = 21
test = MinMaxScalerFile.transform([[1.62,64,21]])

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

In [27]:
test[0]

array([0.32075472, 0.18656716, 0.14893617])

In [28]:
test[0][1]

0.18656716417910446

In [29]:
row =[0,0.3275472,0.18656716,0.14893617,1,0,2,0,0,3,3,]
loaded_model.predict([row])

/Users/ash/opt/anaconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([1])